package com.ssa.pojo;

import java.util.Date;

public class ClockIn extends BaseBean{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock_in.id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock_in.user_id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock_in.type
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock_in.start_time
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock_in.end_time
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock_in.distance
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private String distance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock_in.start_lng
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private String startLng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock_in.end_lng
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private String endLng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock_in.start_lat
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private String startLat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock_in.end_lat
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private String endLat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock_in.calorie
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private String calorie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock_in.create_time
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock_in.id
     *
     * @return the value of clock_in.id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock_in.id
     *
     * @param id the value for clock_in.id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock_in.user_id
     *
     * @return the value of clock_in.user_id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock_in.user_id
     *
     * @param userId the value for clock_in.user_id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock_in.type
     *
     * @return the value of clock_in.type
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock_in.type
     *
     * @param type the value for clock_in.type
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock_in.start_time
     *
     * @return the value of clock_in.start_time
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock_in.start_time
     *
     * @param startTime the value for clock_in.start_time
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock_in.end_time
     *
     * @return the value of clock_in.end_time
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock_in.end_time
     *
     * @param endTime the value for clock_in.end_time
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock_in.distance
     *
     * @return the value of clock_in.distance
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public String getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock_in.distance
     *
     * @param distance the value for clock_in.distance
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setDistance(String distance) {
        this.distance = distance == null ? null : distance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock_in.start_lng
     *
     * @return the value of clock_in.start_lng
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public String getStartLng() {
        return startLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock_in.start_lng
     *
     * @param startLng the value for clock_in.start_lng
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setStartLng(String startLng) {
        this.startLng = startLng == null ? null : startLng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock_in.end_lng
     *
     * @return the value of clock_in.end_lng
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public String getEndLng() {
        return endLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock_in.end_lng
     *
     * @param endLng the value for clock_in.end_lng
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setEndLng(String endLng) {
        this.endLng = endLng == null ? null : endLng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock_in.start_lat
     *
     * @return the value of clock_in.start_lat
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public String getStartLat() {
        return startLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock_in.start_lat
     *
     * @param startLat the value for clock_in.start_lat
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setStartLat(String startLat) {
        this.startLat = startLat == null ? null : startLat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock_in.end_lat
     *
     * @return the value of clock_in.end_lat
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public String getEndLat() {
        return endLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock_in.end_lat
     *
     * @param endLat the value for clock_in.end_lat
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setEndLat(String endLat) {
        this.endLat = endLat == null ? null : endLat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock_in.calorie
     *
     * @return the value of clock_in.calorie
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public String getCalorie() {
        return calorie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock_in.calorie
     *
     * @param calorie the value for clock_in.calorie
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setCalorie(String calorie) {
        this.calorie = calorie == null ? null : calorie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock_in.create_time
     *
     * @return the value of clock_in.create_time
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock_in.create_time
     *
     * @param createTime the value for clock_in.create_time
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}