package com.ssa.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ClockInExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clock_in
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clock_in
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clock_in
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clock_in
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public ClockInExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clock_in
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clock_in
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clock_in
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clock_in
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clock_in
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clock_in
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clock_in
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clock_in
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clock_in
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clock_in
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clock_in
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andDistanceIsNull() {
            addCriterion("distance is null");
            return (Criteria) this;
        }

        public Criteria andDistanceIsNotNull() {
            addCriterion("distance is not null");
            return (Criteria) this;
        }

        public Criteria andDistanceEqualTo(String value) {
            addCriterion("distance =", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceNotEqualTo(String value) {
            addCriterion("distance <>", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceGreaterThan(String value) {
            addCriterion("distance >", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceGreaterThanOrEqualTo(String value) {
            addCriterion("distance >=", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceLessThan(String value) {
            addCriterion("distance <", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceLessThanOrEqualTo(String value) {
            addCriterion("distance <=", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceLike(String value) {
            addCriterion("distance like", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceNotLike(String value) {
            addCriterion("distance not like", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceIn(List<String> values) {
            addCriterion("distance in", values, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceNotIn(List<String> values) {
            addCriterion("distance not in", values, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceBetween(String value1, String value2) {
            addCriterion("distance between", value1, value2, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceNotBetween(String value1, String value2) {
            addCriterion("distance not between", value1, value2, "distance");
            return (Criteria) this;
        }

        public Criteria andStartLngIsNull() {
            addCriterion("start_lng is null");
            return (Criteria) this;
        }

        public Criteria andStartLngIsNotNull() {
            addCriterion("start_lng is not null");
            return (Criteria) this;
        }

        public Criteria andStartLngEqualTo(String value) {
            addCriterion("start_lng =", value, "startLng");
            return (Criteria) this;
        }

        public Criteria andStartLngNotEqualTo(String value) {
            addCriterion("start_lng <>", value, "startLng");
            return (Criteria) this;
        }

        public Criteria andStartLngGreaterThan(String value) {
            addCriterion("start_lng >", value, "startLng");
            return (Criteria) this;
        }

        public Criteria andStartLngGreaterThanOrEqualTo(String value) {
            addCriterion("start_lng >=", value, "startLng");
            return (Criteria) this;
        }

        public Criteria andStartLngLessThan(String value) {
            addCriterion("start_lng <", value, "startLng");
            return (Criteria) this;
        }

        public Criteria andStartLngLessThanOrEqualTo(String value) {
            addCriterion("start_lng <=", value, "startLng");
            return (Criteria) this;
        }

        public Criteria andStartLngLike(String value) {
            addCriterion("start_lng like", value, "startLng");
            return (Criteria) this;
        }

        public Criteria andStartLngNotLike(String value) {
            addCriterion("start_lng not like", value, "startLng");
            return (Criteria) this;
        }

        public Criteria andStartLngIn(List<String> values) {
            addCriterion("start_lng in", values, "startLng");
            return (Criteria) this;
        }

        public Criteria andStartLngNotIn(List<String> values) {
            addCriterion("start_lng not in", values, "startLng");
            return (Criteria) this;
        }

        public Criteria andStartLngBetween(String value1, String value2) {
            addCriterion("start_lng between", value1, value2, "startLng");
            return (Criteria) this;
        }

        public Criteria andStartLngNotBetween(String value1, String value2) {
            addCriterion("start_lng not between", value1, value2, "startLng");
            return (Criteria) this;
        }

        public Criteria andEndLngIsNull() {
            addCriterion("end_lng is null");
            return (Criteria) this;
        }

        public Criteria andEndLngIsNotNull() {
            addCriterion("end_lng is not null");
            return (Criteria) this;
        }

        public Criteria andEndLngEqualTo(String value) {
            addCriterion("end_lng =", value, "endLng");
            return (Criteria) this;
        }

        public Criteria andEndLngNotEqualTo(String value) {
            addCriterion("end_lng <>", value, "endLng");
            return (Criteria) this;
        }

        public Criteria andEndLngGreaterThan(String value) {
            addCriterion("end_lng >", value, "endLng");
            return (Criteria) this;
        }

        public Criteria andEndLngGreaterThanOrEqualTo(String value) {
            addCriterion("end_lng >=", value, "endLng");
            return (Criteria) this;
        }

        public Criteria andEndLngLessThan(String value) {
            addCriterion("end_lng <", value, "endLng");
            return (Criteria) this;
        }

        public Criteria andEndLngLessThanOrEqualTo(String value) {
            addCriterion("end_lng <=", value, "endLng");
            return (Criteria) this;
        }

        public Criteria andEndLngLike(String value) {
            addCriterion("end_lng like", value, "endLng");
            return (Criteria) this;
        }

        public Criteria andEndLngNotLike(String value) {
            addCriterion("end_lng not like", value, "endLng");
            return (Criteria) this;
        }

        public Criteria andEndLngIn(List<String> values) {
            addCriterion("end_lng in", values, "endLng");
            return (Criteria) this;
        }

        public Criteria andEndLngNotIn(List<String> values) {
            addCriterion("end_lng not in", values, "endLng");
            return (Criteria) this;
        }

        public Criteria andEndLngBetween(String value1, String value2) {
            addCriterion("end_lng between", value1, value2, "endLng");
            return (Criteria) this;
        }

        public Criteria andEndLngNotBetween(String value1, String value2) {
            addCriterion("end_lng not between", value1, value2, "endLng");
            return (Criteria) this;
        }

        public Criteria andStartLatIsNull() {
            addCriterion("start_lat is null");
            return (Criteria) this;
        }

        public Criteria andStartLatIsNotNull() {
            addCriterion("start_lat is not null");
            return (Criteria) this;
        }

        public Criteria andStartLatEqualTo(String value) {
            addCriterion("start_lat =", value, "startLat");
            return (Criteria) this;
        }

        public Criteria andStartLatNotEqualTo(String value) {
            addCriterion("start_lat <>", value, "startLat");
            return (Criteria) this;
        }

        public Criteria andStartLatGreaterThan(String value) {
            addCriterion("start_lat >", value, "startLat");
            return (Criteria) this;
        }

        public Criteria andStartLatGreaterThanOrEqualTo(String value) {
            addCriterion("start_lat >=", value, "startLat");
            return (Criteria) this;
        }

        public Criteria andStartLatLessThan(String value) {
            addCriterion("start_lat <", value, "startLat");
            return (Criteria) this;
        }

        public Criteria andStartLatLessThanOrEqualTo(String value) {
            addCriterion("start_lat <=", value, "startLat");
            return (Criteria) this;
        }

        public Criteria andStartLatLike(String value) {
            addCriterion("start_lat like", value, "startLat");
            return (Criteria) this;
        }

        public Criteria andStartLatNotLike(String value) {
            addCriterion("start_lat not like", value, "startLat");
            return (Criteria) this;
        }

        public Criteria andStartLatIn(List<String> values) {
            addCriterion("start_lat in", values, "startLat");
            return (Criteria) this;
        }

        public Criteria andStartLatNotIn(List<String> values) {
            addCriterion("start_lat not in", values, "startLat");
            return (Criteria) this;
        }

        public Criteria andStartLatBetween(String value1, String value2) {
            addCriterion("start_lat between", value1, value2, "startLat");
            return (Criteria) this;
        }

        public Criteria andStartLatNotBetween(String value1, String value2) {
            addCriterion("start_lat not between", value1, value2, "startLat");
            return (Criteria) this;
        }

        public Criteria andEndLatIsNull() {
            addCriterion("end_lat is null");
            return (Criteria) this;
        }

        public Criteria andEndLatIsNotNull() {
            addCriterion("end_lat is not null");
            return (Criteria) this;
        }

        public Criteria andEndLatEqualTo(String value) {
            addCriterion("end_lat =", value, "endLat");
            return (Criteria) this;
        }

        public Criteria andEndLatNotEqualTo(String value) {
            addCriterion("end_lat <>", value, "endLat");
            return (Criteria) this;
        }

        public Criteria andEndLatGreaterThan(String value) {
            addCriterion("end_lat >", value, "endLat");
            return (Criteria) this;
        }

        public Criteria andEndLatGreaterThanOrEqualTo(String value) {
            addCriterion("end_lat >=", value, "endLat");
            return (Criteria) this;
        }

        public Criteria andEndLatLessThan(String value) {
            addCriterion("end_lat <", value, "endLat");
            return (Criteria) this;
        }

        public Criteria andEndLatLessThanOrEqualTo(String value) {
            addCriterion("end_lat <=", value, "endLat");
            return (Criteria) this;
        }

        public Criteria andEndLatLike(String value) {
            addCriterion("end_lat like", value, "endLat");
            return (Criteria) this;
        }

        public Criteria andEndLatNotLike(String value) {
            addCriterion("end_lat not like", value, "endLat");
            return (Criteria) this;
        }

        public Criteria andEndLatIn(List<String> values) {
            addCriterion("end_lat in", values, "endLat");
            return (Criteria) this;
        }

        public Criteria andEndLatNotIn(List<String> values) {
            addCriterion("end_lat not in", values, "endLat");
            return (Criteria) this;
        }

        public Criteria andEndLatBetween(String value1, String value2) {
            addCriterion("end_lat between", value1, value2, "endLat");
            return (Criteria) this;
        }

        public Criteria andEndLatNotBetween(String value1, String value2) {
            addCriterion("end_lat not between", value1, value2, "endLat");
            return (Criteria) this;
        }

        public Criteria andCalorieIsNull() {
            addCriterion("calorie is null");
            return (Criteria) this;
        }

        public Criteria andCalorieIsNotNull() {
            addCriterion("calorie is not null");
            return (Criteria) this;
        }

        public Criteria andCalorieEqualTo(String value) {
            addCriterion("calorie =", value, "calorie");
            return (Criteria) this;
        }

        public Criteria andCalorieNotEqualTo(String value) {
            addCriterion("calorie <>", value, "calorie");
            return (Criteria) this;
        }

        public Criteria andCalorieGreaterThan(String value) {
            addCriterion("calorie >", value, "calorie");
            return (Criteria) this;
        }

        public Criteria andCalorieGreaterThanOrEqualTo(String value) {
            addCriterion("calorie >=", value, "calorie");
            return (Criteria) this;
        }

        public Criteria andCalorieLessThan(String value) {
            addCriterion("calorie <", value, "calorie");
            return (Criteria) this;
        }

        public Criteria andCalorieLessThanOrEqualTo(String value) {
            addCriterion("calorie <=", value, "calorie");
            return (Criteria) this;
        }

        public Criteria andCalorieLike(String value) {
            addCriterion("calorie like", value, "calorie");
            return (Criteria) this;
        }

        public Criteria andCalorieNotLike(String value) {
            addCriterion("calorie not like", value, "calorie");
            return (Criteria) this;
        }

        public Criteria andCalorieIn(List<String> values) {
            addCriterion("calorie in", values, "calorie");
            return (Criteria) this;
        }

        public Criteria andCalorieNotIn(List<String> values) {
            addCriterion("calorie not in", values, "calorie");
            return (Criteria) this;
        }

        public Criteria andCalorieBetween(String value1, String value2) {
            addCriterion("calorie between", value1, value2, "calorie");
            return (Criteria) this;
        }

        public Criteria andCalorieNotBetween(String value1, String value2) {
            addCriterion("calorie not between", value1, value2, "calorie");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clock_in
     *
     * @mbg.generated do_not_delete_during_merge Thu May 07 20:02:50 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clock_in
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}