package com.ssa.pojo;

import java.util.Date;

public class DynamicComment extends BaseBean{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic_comment.id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic_comment.dynamic_id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private Integer dynamicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic_comment.msg
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private String msg;
    private Long userId;

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic_comment.create_time
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic_comment.id
     *
     * @return the value of dynamic_comment.id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic_comment.id
     *
     * @param id the value for dynamic_comment.id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic_comment.dynamic_id
     *
     * @return the value of dynamic_comment.dynamic_id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public Integer getDynamicId() {
        return dynamicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic_comment.dynamic_id
     *
     * @param dynamicId the value for dynamic_comment.dynamic_id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setDynamicId(Integer dynamicId) {
        this.dynamicId = dynamicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic_comment.msg
     *
     * @return the value of dynamic_comment.msg
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic_comment.msg
     *
     * @param msg the value for dynamic_comment.msg
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic_comment.create_time
     *
     * @return the value of dynamic_comment.create_time
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic_comment.create_time
     *
     * @param createTime the value for dynamic_comment.create_time
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}