package com.ssa.pojo;

public class DynamicLike extends BaseBean{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic_like.id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic_like.user_id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic_like.dynamic_id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private Long dynamicId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic_like.id
     *
     * @return the value of dynamic_like.id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic_like.id
     *
     * @param id the value for dynamic_like.id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic_like.user_id
     *
     * @return the value of dynamic_like.user_id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic_like.user_id
     *
     * @param userId the value for dynamic_like.user_id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic_like.dynamic_id
     *
     * @return the value of dynamic_like.dynamic_id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public Long getDynamicId() {
        return dynamicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic_like.dynamic_id
     *
     * @param dynamicId the value for dynamic_like.dynamic_id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setDynamicId(Long dynamicId) {
        this.dynamicId = dynamicId;
    }
}