package com.ssa.pojo;

import java.util.Date;

public class Dynamic extends BaseBean{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.name
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private String name;
    private String headImg;

    public String getHeadImg() {
        return headImg;
    }

    public void setHeadImg(String headImg) {
        this.headImg = headImg;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.title
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.img
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.content
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.like_count
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.view_count
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private Integer viewCount;
    private Long userId;

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.create_time
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.id
     *
     * @return the value of dynamic.id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.id
     *
     * @param id the value for dynamic.id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.name
     *
     * @return the value of dynamic.name
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.name
     *
     * @param name the value for dynamic.name
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.title
     *
     * @return the value of dynamic.title
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.title
     *
     * @param title the value for dynamic.title
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.img
     *
     * @return the value of dynamic.img
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.img
     *
     * @param img the value for dynamic.img
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.content
     *
     * @return the value of dynamic.content
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.content
     *
     * @param content the value for dynamic.content
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.like_count
     *
     * @return the value of dynamic.like_count
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.like_count
     *
     * @param likeCount the value for dynamic.like_count
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.view_count
     *
     * @return the value of dynamic.view_count
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.view_count
     *
     * @param viewCount the value for dynamic.view_count
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.create_time
     *
     * @return the value of dynamic.create_time
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.create_time
     *
     * @param createTime the value for dynamic.create_time
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}