package com.ssa.pojo;

import java.util.Date;

public class Feedback extends BaseBean{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.user_id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.feedback
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private String feedback;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.reply
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private String reply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.create_time
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.id
     *
     * @return the value of feedback.id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.id
     *
     * @param id the value for feedback.id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.user_id
     *
     * @return the value of feedback.user_id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.user_id
     *
     * @param userId the value for feedback.user_id
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.feedback
     *
     * @return the value of feedback.feedback
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public String getFeedback() {
        return feedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.feedback
     *
     * @param feedback the value for feedback.feedback
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setFeedback(String feedback) {
        this.feedback = feedback == null ? null : feedback.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.reply
     *
     * @return the value of feedback.reply
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public String getReply() {
        return reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.reply
     *
     * @param reply the value for feedback.reply
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setReply(String reply) {
        this.reply = reply == null ? null : reply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.create_time
     *
     * @return the value of feedback.create_time
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.create_time
     *
     * @param createTime the value for feedback.create_time
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}