package com.ssa.mapper;

import com.ssa.pojo.DynamicLike;
import com.ssa.pojo.DynamicLikeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DynamicLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_like
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    long countByExample(DynamicLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_like
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    int deleteByExample(DynamicLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_like
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_like
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    int insert(DynamicLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_like
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    int insertSelective(DynamicLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_like
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    List<DynamicLike> selectByExample(DynamicLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_like
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    DynamicLike selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_like
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    int updateByExampleSelective(@Param("record") DynamicLike record, @Param("example") DynamicLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_like
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    int updateByExample(@Param("record") DynamicLike record, @Param("example") DynamicLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_like
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    int updateByPrimaryKeySelective(DynamicLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_like
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    int updateByPrimaryKey(DynamicLike record);

    List<DynamicLike> getAllByLimit(DynamicLike pojo);

    int countAllByLimit(DynamicLike pojo);
}