package com.ssa.mapper;

import com.ssa.pojo.Dynamic;
import com.ssa.pojo.DynamicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DynamicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    long countByExample(DynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    int deleteByExample(DynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    int insert(Dynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    int insertSelective(Dynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    List<Dynamic> selectByExample(DynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    Dynamic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    int updateByExampleSelective(@Param("record") Dynamic record, @Param("example") DynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    int updateByExample(@Param("record") Dynamic record, @Param("example") DynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    int updateByPrimaryKeySelective(Dynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    int updateByPrimaryKey(Dynamic record);

    List<Dynamic> getAllByLimit(Dynamic pojo);

    int countAllByLimit(Dynamic pojo);
}