package com.ssa.mapper;

import com.ssa.pojo.ClockIn;
import com.ssa.pojo.DynamicComment;
import com.ssa.pojo.DynamicCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DynamicCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_comment
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    long countByExample(DynamicCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_comment
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    int deleteByExample(DynamicCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_comment
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_comment
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    int insert(DynamicComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_comment
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    int insertSelective(DynamicComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_comment
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    List<DynamicComment> selectByExample(DynamicCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_comment
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    DynamicComment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_comment
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    int updateByExampleSelective(@Param("record") DynamicComment record, @Param("example") DynamicCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_comment
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    int updateByExample(@Param("record") DynamicComment record, @Param("example") DynamicCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_comment
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    int updateByPrimaryKeySelective(DynamicComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_comment
     *
     * @mbg.generated Thu May 07 20:02:50 CST 2020
     */
    int updateByPrimaryKey(DynamicComment record);

    List<DynamicComment> getAllByLimit(DynamicComment pojo);

    int countAllByLimit(DynamicComment pojo);
}